# Setup
title:                Galerie Arts et multim√©dia
tagline:             ''
description:         ''
url:                 https://artsmulti.github.io
baseurl:             '/galerie_cal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
